### ISSUE TITLE
공연 예약 API 설계

### ISSUE THREAD

**Issue by comento-yun** [comento-backend-camp/ticket-reservation-server-minji#1]

**Comment by minji128** [comment]
# 공연 예약 시스템 : Performance Booking System

> **기능적 요구사항**

    • 사용자는 공연 정보를 조회할 수 있다. (공연은 제목,공연일,가격,상세정보내용을 포함)
    • 사용자는 공연을 선택하면 선택한 공연에 대한 좌석정보를 조회할 수 있다.
    • 사용자는 자신이 예매한 공연의 예약정보를 조회할 수 있다.
    • 좌석은 VIP석,S석,A석,B석,C석이 있고 각 20자리의 좌석이 있다.
    • 회원원가입과 회원인증은 별도로 필요없고 이메일 정보를 시스템에 등록할 수 있다.
    • 이메일을 등록한 사용자는 공연 좌석을 예약을 할 수 있다.
    • 모든 공연 예매요청(성공 혹은 실패) 시도는 reservation_history테이블에 기록해야한다.

> **비기능적 요구사항**

    • (Optional) 모든 기능에는 테스트가 작성되어야 합니다. TDD를 하지 않더라도 테스트 코드를 작성해보도록 노력합니다.
    • 시스템의 사용은 REST API로 통신
    • 공연일이 지난 공연은 예약을 할 수 없다.
    • 시스템은 두 명의 고객이 같은 좌석을 예약할 수 없도록 해야 한다.
    • 이메일을 등록하지 않은 요청은 예약을 성공할 수 없다.
    • Spring Framework과 MySQL를 이용해서 api를 개발합니다.

</br>

## Usecase Diagram
> **주요 액터**

    •  Client : 공연 일정 조회, 좌석 조회, 공연 예매/조회 가능, 이메일을 등록한 회원
    •  Guest : 공연 일정 및 좌석 조회는 가능하지만, 공연을 예매하려면 이메일을 등록한 회원이어야 함

> **주요 기능**

    • 공연 정보 조회
    • 선택한 공연에 대한 좌석 정보 조회
    • 공연 예약
    • 예약할 공연 좌석 지정
    • 예약한 공연 조회

![Usecase Diagram](https://user-images.githubusercontent.com/48500366/132232374-0bdc1575-f397-4460-b111-78e661a40e8e.png)

<br>

## Class Diagram
> **주요 클래스**

    • Guest : 공연 정보 조회, 좌석 조회 가능, 공연 예약을 위해 회원으로 등록해야 함
    • Client : 이메일 등록, 모든 기능 가능
    • Performance : 제목, 공연일, 가격, 상세정보내용
    • Seat : 선택한 영화의 좌석 정보, VIP석/S석/A석/B석/C석 각 20자리의 좌석 존재, 좌석 넘버, 좌석등급, 예약여부, 가격
    • Booking : 공연 예매, 고유한 예약번호, 좌석 수 및 상태
    • payment : 공연을 예매를 위한 결제

![Class Diagram](https://user-images.githubusercontent.com/48500366/132232855-abb61a11-9d54-4dac-9bf3-b9fe338ad337.png)

## Sequence Diagram
> **이메일 등록**

![시퀀스-이메일등록](https://user-images.githubusercontent.com/48500366/132233267-ec44d587-8ff9-4bad-9574-84359706db35.png)

> **공연 정보 조회**

![시퀀스-공연정보조회](https://user-images.githubusercontent.com/48500366/132233543-78eac43b-b519-4185-8109-cb71eafdaa0a.png)

> **좌석 정보 조회**

![시퀀스-좌석정보조회](https://user-images.githubusercontent.com/48500366/132233695-480c45b4-9865-461b-9ffc-e8aef0e246f1.png)

**Comment by minji128** [comment]
API설계를 처음해보는 것이어서, 좀 더 공부한 후 보충하여 올리겠습니다.

**Comment by comento-yun** [comment]
@minji128 님, 1주차 과제 수행한다고 고생 많으셨습니다. 일단 1차 피드백 드리고 추가적으로 피드백할 내용 있으면 계속 피드백 남기겠습니다. 다이어그램 그리는게 익숙하지 않았다면 조금은 힘들수 있는 과제 였는데 잘 수행하셨습니다. 리뷰 남겼으니 확인 부탁드립니다 !

실제로 시스템을 설계할때 개발자간의 리뷰 혹은 개발자와 기획자간의 의사소통을 위해서 유즈케이스,시퀀스,클래스 다이어그램을 사용합니다.!  이번기회에 다이어그램에 대해서 조금이나마 이해하셔서 도움이 되면 좋겠습니다.

## End-User에게 제공할 HTTP Method를 포함한 API 설계하기

end user에게 제공할 HTTP REST API에 대한 명세가 빠져있습니다. 모든 조건을 충족하는 Restful한 API를 만드는것은 정말 어려운데요.  최대한 Restful하게 http api를 명세해주면 해당 백엔드 API를 사용할 프론트엔드 개발자는 HTTP API만 보고도 대부분의 기능을 유추할 수 있습니다 .

그런 REST API로 괜찮은가? ([https://www.youtube.com/watch?v=RP_f5dMoHFc](https://www.youtube.com/watch?v=RP_f5dMoHFc)) 라는 영상인데 우리가 설계하는 대부분의 API는 REST API가 아니라 HTTP API라는것을 알려주는 영상입니다. 영상에서 말하는 정말 Restful한 API를 설계하는것은 쉽지 않기 때문에 HTTP GET,POST,PUT,DELETE메서드를 활용하고 명사형으로 url을 표기해서 조금이나마 restful한 http api를 설계해보면 좋을것 같아요.!

## System Architecture 설계하기

시스템 아키텍처는 시스템 수준에서 확인 가능한 설계도 입니다.  현재 여러 다이어그램을 통해서 애플리케이션 레벨의 설계는 확인했는데 해당 애플리케이션을 어떤 형태로 구성할지에 대해서 시스템 아키텍쳐를 그려주시면 해당 문서를 읽어보는 다른 개발자는 더 이해하기 쉽고, 운영간 이슈를 쉽게 파악할 수 있을것 같습니다.

앞단에서 모든 요청을 받아주는 Apache나 Nginx같은 웹서버를 두고  웹서버에서 Spring Boot로 개발한 웹애플리케이션 서버(WAS)에게 요청을 전달해 주는 간단한 구조로 그려주셔도 좋습니다.

## Usecase Diagram

- `액터`는 개발할 시스템의 외부 존재인 점을 생각할때 시스템을 사용하는 Customer,Guest로 구분을 잘 하셨습니다. 👍
- 좌석을 조회하면 공연정보를 조회할 수 있을까요? 아니면 공연정보를 조회하면 좌석을 조회할 수 있을까요?include(포함관계)의 방향이 반대방향으로 표시되어야 하지 않을까 생각합니다.
- "회원가입과 회원인증은 별도로 필요없고 이메일 정보를 시스템에 등록할 수 있다." 라는 요구사항에 의하면  Register email 유즈케이스는 액터가 수행할 수 있는 독립적인 유즈케이스로 식별되는것 같아요~!

## Class Diagram

- `UrlController`라는 객체가 보이는데 UrlController의 역할이 클래스명만 보면 떠오르지가 않습니다. 만약 오타라면 수정 부탁드립니다!
- `UrlController`에서는 현재 `단일 책임원칙`을 위반하고 있습니다. 즉, 공연조회,공연좌석조회, 예약,예약정보조회,이메일 등록을 모두 수행하고 잇는 God Object가 되었는데요. 컨트롤러를 분리하면 어떨까요? 현재 수준에서는 문제가 되지 않지만 다른 개발자가 갑자기 투입되면 기존에 만들어진 코드를 관습대로 작성하는 상황이 많이 발생합니다. 즉 모든 로직이 UrlController에 작성될 가능성이 발생합니다.
    - PerformanceController
    - BookingController
    - MemberController
- 고객을 지칭하는 `Client`대신 `Customer`혹은 `Member`라는 표현을 사용하면 어떨까요??
    - Client는 엔터프라이즈 환경에서 사용하는 프레임워크 혹은 라이브러리에서 외부 API를 호출할때 xxxClient라는 네이밍을 많이 붙여서 사용합니다. 예를들어 네이버 뉴스를 조회하는 API가 필요해서 네이버 API를 호출할때 NaverClient같은 네이밍을 붙이기도 합니다.
    - spring에서 많이 사용하는 Open Feign 이라는 도구 역시 xxClient라는 네이밍으로 외부 api를 지칭하고 있습니다. (https://cloud.spring.io/spring-cloud-netflix/multi/multi_spring-cloud-feign.html#:~:text=%40FeignClient(%22stores%22)-,public%20interface%20StoreClient,-%7B%0A%20%20%20%20%40RequestMapping(method%20%3D%20RequestMethod)
- `Client`에는 현재 email이라는 값만 가지고 있네요, 아직 테이블 설계를 진행한것은 아니지만 현재 구조를 보면 jpa를 사용하고 도메인 모델을 entity로 표현하고 있는것 같습니다. 비즈니스의 성공으로 시스템이 확장하고 이메일을 fk로 사용하는 테이블이 있는데 갑자기 정부의 보안정책 강화로 "웹서비스에서는 이메일 정보를 입력받는것은 불법이다" 라는 법안이 나오게 되면 시스템 전체를 수정해야하는 불상사가 생길수 있습니다. 해당 글을 확인해보고 인조키를 사용하는 엔티티로 수정해보면 좋을것 같습니다.   [https://multifrontgarden.tistory.com/180](https://multifrontgarden.tistory.com/180)

## Sequence Diagram

시퀀스 다이어그램은 기획자분들도 이해하기 때문에, 시퀀스 다이어그램으로 비즈니스 로직을 설명하기도 합니다. 현재 이메일등록,공연정보 조회,좌석정보 조회 시퀀스다이어그램을 눈으로 읽어만 봐도 어떤 관계로 로직이 진행되는지 한눈에 파악되게 잘 작성해주신것 같습니다. :)

아래 내용은 개선하면 더 좋아질것 같은 내용입니다.

- 좌석 정보 조회 시퀀스 다이어그램
    - 클래스다이어그램에서는 식별하지 못한 문제를 시퀀스다이어그램에서 식별했습니다. 현재 Controller에서 PerformanceService를 통해서 Performace 엔티티를 조회하고 SeatService를 통해 공연의 Seat을 조회해서 응답갑을 만들어서 리턴하고 있네요.
    - 컨트롤러레이어는 요청값의 validation, 응답값 response수준의 로직만 들어가는게 바람직 합니다. 컨트롤러단에서 위와 같은 aggregate 행위가 발생하면 컨트롤러 레이어가 오염될 가능성 발생합니다.
    - PerformanceSeatFinderService와 같은 또다른 서비스 계층을 만들고 해당 서비스에서 공연의 ID만 넘겨주면 바로 공연과 공연의 좌석을 aggregate시켜서 응답해주는 별도의 서비스를 만들면 위의 문제를 해결할 수 있습니다.
- 이메일 등록, 공연정보 조회, 좌석정보 조회의 시퀀스 다이어그램만 있는데 view booking, create booking의 시퀀스 다이어그램은 빠진것 같습니다. 추가부탁드립니다.

**Comment by minji128** [comment]
# 공연 예약 시스템 : Ticket Reservation System

> **기능적 요구사항**

    • 사용자는 공연 정보를 조회할 수 있다. (공연은 제목,공연일,가격,상세정보내용을 포함)
    • 사용자는 공연을 선택하면 선택한 공연에 대한 좌석정보를 조회할 수 있다.
    • 사용자는 자신이 예매한 공연의 예약정보를 조회할 수 있다.
    • 좌석은 VIP석,S석,A석,B석,C석이 있고 각 20자리의 좌석이 있다.
    • 회원원가입과 회원인증은 별도로 필요없고 이메일 정보를 시스템에 등록할 수 있다.
    • 이메일을 등록한 사용자는 공연 좌석을 예약을 할 수 있다.
    • 모든 공연 예매요청(성공 혹은 실패) 시도는 reservation_history테이블에 기록해야한다.

> **비기능적 요구사항**

    • (Optional) 모든 기능에는 테스트가 작성되어야 합니다. TDD를 하지 않더라도 테스트 코드를 작성해보도록 노력합니다.
    • 시스템의 사용은 REST API로 통신
    • 공연일이 지난 공연은 예약을 할 수 없다.
    • 시스템은 두 명의 고객이 같은 좌석을 예약할 수 없도록 해야 한다.
    • 이메일을 등록하지 않은 요청은 예약을 성공할 수 없다.
    • Spring Framework과 MySQL를 이용해서 api를 개발합니다.
</br>

## API 설계
[API 설계문서 링크](https://pond-bottom-82a.notion.site/1-API-a50ad2c0851645ef8329eb9d1a41270d)
</br>

## Usecase Diagram
> **주요 액터**

    •  회원 : 공연 일정 조회, 좌석 조회, 공연 예매/조회 가능, 이메일을 등록한 회원
    •  비회원 : 공연 일정 및 좌석 조회는 가능하지만, 공연을 예매하려면 이메일을 등록한 회원이어야 함

> **주요 기능**

    • 공연 정보 조회
    • 선택한 공연에 대한 좌석 정보 조회
    • 이메일 등록
    • 이메일 인증
    • 공연 예약
    • 예약할 공연 좌석 지정
    • 예약한 공연 조회

![유스케이스](https://user-images.githubusercontent.com/48500366/133006392-2a482e47-d88f-4d8a-a2b2-1fde1825e66b.png)

<br>

## Class Diagram
> **주요 클래스**

    • Guest : 공연 정보 조회, 좌석 조회 가능, 공연 예약을 위해 회원으로 등록해야 함
    • Member : 이메일 등록, 모든 기능 가능
    • Performance : 제목, 공연일, 가격, 상세정보내용
    • Booking : 회원정보, 공연정보, 좌석유형, 좌석번호

![클래스다이어그램](https://user-images.githubusercontent.com/48500366/133005463-33f6df21-a294-49b0-9093-be4a8705f87d.png)


<br>

## Sequence Diagram
> **이메일 등록**

![시퀀스-이메일등록](https://user-images.githubusercontent.com/48500366/133005123-4873feb6-657e-462d-93bd-8d73975c8861.png)


> **이메일 인증**

![시퀀스-이메일인증](https://user-images.githubusercontent.com/48500366/133005093-c75e4904-fac6-43b7-9987-0fd642a37418.png)

> **공연 정보 조회**

![시퀀스-공연정보조회](https://user-images.githubusercontent.com/48500366/133005658-734ee3c5-5caf-4995-aa0c-75e8e25bf28b.png)

> **좌석 정보 조회**

![시퀀스-좌석정보조회](https://user-images.githubusercontent.com/48500366/133005802-efac87c7-f01a-4e49-b988-527b3f25a946.png)

> **공연 예약**

![시퀀스-공연 예약](https://user-images.githubusercontent.com/48500366/133005985-5aa2a9fb-ec04-40aa-a454-35ee6a699cbd.png)

> **예약 공연 정보 조회**

![시퀀스-예약 공연 조회](https://user-images.githubusercontent.com/48500366/133006183-4d2853b8-2659-41b4-8ff3-fd43a778e9e9.png)

**Comment by minji128** [comment]
피드백 반영하여 수정했습니다.

**Comment by comento-yun** [comment]
@minji128  

고생하셨습니다. 

유즈케이스에서 이메일 등록을 별도의 케이스로 잘 식별하셨고 member라는 네이밍 변경 및 member pk추가도 잘 하셨습니다. 클래스도 관심사에 맞게 잘 분리하셨습니다.!
