### ISSUE TITLE
공연 예약 API 설계 2 : DFD, DB 설계, 트랜잭션과 락 정리

### ISSUE THREAD

**Issue by minji128** [comento-backend-camp/ticket-reservation-server-minji#2]
# 공연 예약 API 설계 2

    1. DFD 설계
    2. DB 설계
    3. RDBMS의 트랜잭션과 락
    4. Spring에서 제공하는 트랜잭션
<br>

## DFD 설계

![DFD](https://user-images.githubusercontent.com/48500366/133078264-ee4163c1-ac4f-4439-b6b7-7bfedcd3f188.png)
<br>

## DB설계

![DB](https://user-images.githubusercontent.com/48500366/133078688-7b31430d-aa17-49fc-a0f8-9e775b7cf178.png)
<br>

**Comment by minji128** [comment]
## RDBMS의 트랜잭션과 락
### 1. 트랜잭션의 개념
>**정의**
- 데이터 베이스의 상태를 변화시키기 위해서 수행하는 작업의 단위
    → 변화 : SELECT, INSERT, DELETE, UPDATE 와 같은 질의어(SQL)를 이용하여 DB에 접근하는 것
> **특징**
1. 원자성(Atomicity)
    - 트랙잭션이 DB에 모두 반영되던가, 아니면 전혀 반영되지 않아야 한다는 것
2. 일관성(Consistency)
    - 트랜잭션의 작업 처리 결과가 항상 일관성 있어야 함
    - 트랜잭션이 진행되는 동안 DB가 변경되더라도 업데이트된 DB로 트랜잭션 진행되는 것이 아니라, 처음에 참조한 DB로 진행
3. 독립성(Isolation)
    - 둘 이상의 트랜잭션이 동시에 실행되고 있을 경우 어떤 하나의 트랜색젼이라도, 다른 트랜젹션의 연산에 끼어들 수 없다
    - 즉, 하나의 특정 트랜잭션이 완료될 때 까지 ,다른 트랜잭션이 특정 트랜잭션의 결과를 참조할 수 X
4. 지속성(Durability)
    - 트랜잭션이 성공적으로 완료되었을 경우, 영구적으로 반영되어야 함
> **Commit**
- 하나의 트랜잭션이 성공적으로 끝났고, DB가 일관성 있는 상태에 있을 때, 하나의 트랜잭션이 끝났다라는 것을 알려주기 위한 연산
> **Rollback** 
- 하나의 트랜잭션 처리가 비상적으로 종료되어 트랜잭션의 원자성이 깨진 경우, 트랜잭션을 처음부터 다시 시작하거나, 트랜잭션의 부분적으로만 연산적 결과를 다시 취소시킴

<br>

### 2. RDBMS의 트랜잭션과 락
> **문제 상황**
- 공연 예매시, 특정 좌석에 동시에 접근했을 경우 → 동시성 문제 발생 ⇒ **[해결] 트랜잭션 락**
> **트랜잭션 격리 수준(isolation) 정의**
- 동시에 여러 트랜잭션이 처리될 때, 특정 트랜잭션이 다른 트랜잭션에서 변경하거나 조회하는 데이터를 볼 수 있도록 허용할지 말지를 결정하는 것
> **트랜잭션 격리수준 4가지**
1. **READ UNCOMMITTED**
- 각 트랜잭션에서의 변경 내용이 COMMIT이나 ROLLBACK 여부에 상관 없이 다른 트랜잭션에서 값을 읽을 수 있다.
- 정합성에 문제가 많은 격리 수준이기 때문에 사용하지 않는 것을 권장한다.
- 아래의 그림과 같이 Commit이 되지 않는 상태지만 Update된 값을 다른 트랜잭션에서 읽을 수 있다.
```
[문제점] DIRTY READ 현상 발생
- 트랜잭션이 작업이 완료되지 않았는데도 다른 트랜잭션에서 볼 수 있게 되는 현상
```
<br>

2. **READ COMMIITED**
- RDB에서 대부분 기본적으로 사용되고 있는 격리 수준이다.
- Dirty Read와 같은 현상은 발생하지 않는다.
- 실제 테이블 값을 가져오는 것이 아니라 Undo 영역에 백업된 레코드에서 값을 가져온다.

```
[ 문제점 ]
- 트랜잭션-1이 Commit한 이후 아직 끝나지 않는 트랜잭션-2가 다시 테이블 값을 읽으면 값이 변경됨을 알 수 있다.
- 하나의 트랜잭션내에서 똑같은 SELECT 쿼리를 실행했을 때는 항상 같은 결과를 가져와야 하는 REPEATABLE READ의 정합성에 어긋난다.
- 이러한 문제는 주로 입금, 출금 처리가 진행되는 금전적인 처리에서 주로 발생한다.
- 데이터의 정합성은 깨지고, 버그는 찾기 어려워 진다.
```
<br>

3. **REPEATABLE READ**
- MySQL에서는 트랜잭션마다 트랜잭션 ID를 부여하여 트랜잭션 ID보다 작은 트랜잭션 번호에서 변경한 것만 읽게 된다.
- Undo 공간에 백업해두고 실제 레코드 값을 변경한다.
  - 백업된 데이터는 불필요하다고 판단하는 시점에 주기적으로 삭제
  - Undo에 백업된 레코드가 많아지면 MySQL 서버의 처리 성능이 떨어질 수 있다.
- 이러한 변경방식은 MVCC(Multi Version Concurrency Control)라 부름

```
[ 문제점 ] PHANTOM READ
- 다른 트랜잭션에서 수행한 변경 작업에 의해 레코드가 보였다가 안 보였다가 하는 현상
- 이를 방지하기 위해서는 쓰기 잠금을 걸어야 함
```
<br>

4. **SERIALIZE**
- 가장 단순한 격리 수준이지만 가장 엄격한 격리 수준
- 성능 측면에서는 동시 처리성능이 가장 낮다.
- SERIALIZABLE에서는 PHANTOM READ가 발생하지 않는다.
- 데이터베이스에서 거의 사용되지 않는다.

<br>

## Spring에서 제공하는 트랜잭션
### 1. Spring이 제공하는 Transaction(트랜잭션) 핵심기술 3가지
> **1) 트랜잭션 동기화(Transaction Synchronization)**
- **문제 상황**
    - JDBC를 이용하는 개발자가 직접 여러 개의 작업을 하나의 트랜잭션으로 관리 → Connection 객체를 굥유하는 등 불필요한 작업 생김 ⇒ **해결 : 트랜잭션 동기화**
- **트랜잭션 동기화**
    - 트랜잭션을 시작하기 위한 Connection 객체를 특별한 저장소에 보관해두고 필요할 때 꺼내쓸 수 있도록 하는 기술
    - 트랙잭션 동기화 저장소는 작업 쓰레드 마다 Connection 객체를 독립적으로 관리하기 때문에, 멀티쓰레드 환경에서도 충돌 발생 X
<br>

> **2) 트랜잭션 추상화**
- **문제 상황**
    - JDBC가 아닌 Hibernate 같은 기술 사용 → JDBC 종속적인 트랜잭션 동기화 코드들은 문제 발생 ⇒ **해결 : 트랜잭션 추상화**
    - Hibernate는 Connection가 아닌 Session라는 객체 사용
- **트랜잭션 추상화**
    - Spring은 트랙잭션 기술의 공통점을 담은 트랜잭션 추상화 기술 제공
    - 애플리케이션에 각 기술마다(JDBC, JPA, Hibernate 등) 종속적인 코드를 이용하지 않고도 일관되게 트랙잭션 처리
- **트랙잭션 경계 설정 추상 인터페이스 : PlatformTransactionManager**
    - 추상 인터페이스를 통해 트랙잭션을 공유, 커밋, 롤백할 수 있게 됨
<br>

> **3) AOP를 이용한 트랙잭션 분리**
- **문제 상황**
    - 트랙잭션 관리 코드들이 비지니스 로직 코드와 결합되어 2가지 책임 가짐 ⇒ **해결 : AOP**
- **AOP**
    - 트랙잭션 부분을 핵심 비지니스 로직과 분리
    - 트랙잭션 코드와 같은 부가 기능 코드가 존재하지 않는 것처럼 보이기 위해, 해당 로직을 클래스 밖으로 빼내서 별도의 모듈로 만드는 것
    - 이를 적용한 트랜잭션 어노테이션(@Transactional)을 지원
<br>

### 2. Spring에서 트랜잭션 사용법
> **1) @Transactional 어노테이션(선언적 트랜잭션)**
- Spring에서는 클래스나 인터페이스 또는 메소드에 부여할 수 있는 @Transactional이라는 어노테이션을 제공
- 이 어노테이션이 붙으면 스프링은 해당 타깃을 포인트 컷의 대상으로 자동 등록하며 트랜잭션 관리 대상이 된다. 즉, 이 어노테이션을 통해 포인트 컷에 등록하고 트랜잭션 속성을 부여하는 것
<br>

> **2) Spring에서 트랜잭션의 사용법**
1. **비지니스 로직과의 결합**
- 특정 계층의 경계를 트랜잭션 경계와 일치시키는 것이 좋은데, 일반적으로 비지니스 로직을 담고 있는 서비스 계층의 메소드와 결합시키는 것이 좋음
- 데이터 저장 계층으로부터 읽어온 데이터를 사용하고 변경하는 등의 작업을 하는 곳은 일반적으로 서비스 계층이기 때문 
- 클래스 레벨에 트랜잭션 어노테이션을 붙여주면 메소드까지 적용
```java
@Service
@RequiredArgsConstructor
@Transactional(readOnly = true)
public class UserService {

    private final UserRepository userRepository;
    private final BCryptPasswordEncoder passwordEncoder;

    public List<User> getUserList() {
        return userRepository.findAll();
    }

}
```

<br>

2. **읽기 전용 트랜잭션 공통화**
- 클래스 레벨에는 공통적으로 적용되는 읽기전용 트랜잭션 어노테이션을 선언하고, 추가나 삭제 또는 수정이 있는 작업에는 쓰기가 가능하도록 별도로 @Transacional 어노테이션을 메소드에 선언이 좋음
```java
@Service
@RequiredArgsConstructor
@Transactional(readOnly = true)
public class UserService {

    private final UserRepository userRepository;
    private final BCryptPasswordEncoder passwordEncoder;

    public List<User> getUserList() {
        return userRepository.findAll();
    }

    @Transactional
    public User signUp(final SignUpDTO signUpDTO) {
        final User user = User.builder()
                .email(signUpDTO.getEmail())
                .pw(passwordEncoder.encode(signUpDTO.getPw()))
                .role(UserRole.ROLE_USER)
                .build();

        return userRepository.save(user);
    }
}
```

3. **테스트의 롤백**
- 트랜잭션 어노테이션을 테스트에 붙이면 테스트의 DB 커밋을 롤백해주는 기능
- 테스트를 진행하는 동안에 조작한 데이터를 모두 롤백하고 테스트를 진행하기 전의 상태로 만들어준다. 
-  DB에 반영하고 싶다면 @Rollback(false)를 이용
- 하지만 @Rollback은 메소드에만 적용가능하므로, 클래스 레벨에 부여하기를 원한다면 @TransactionConfiguration(defaultRollback=false) 를 이용하고, 롤백을 원하는 메소드에 @Rollback(true)를 이용
- auto_increment나 sequence 등에 의해 증가된 값은 롤백이 되지 않는다.
```java
@Transactional
@ExtendWith(SpringExtension.class)
@DataJpaTest
class UserRepositoryTest {

    @Autowired
    private UserRepository userRepository;

    @Test
    void findByEmailAndPw() {
        final User user = User.builder()
                .email("email")
                .pw("pw")
                .role(UserRole.ROLE_USER).build();
        userRepository.save(user);

        assertThat(userRepository.findAll().size()).isEqualTo(1);
    }
}
```

**Comment by comento-yun** [comment]
@minji128 님 2주차 과제 고생하셨습니다
민지님께도 질문 몇가지를 남겼으니 이에 대해서 한번 잘 생각해보면 좋을거에요~ 

## 테이블 설계

1. booking테이블 추가컬럼 

아래 피드백은 혜정님께도 피드백으로 남겼던 내용이여서 복사붙여넣기를 했습니다😅
booking테이블에 사용자가 예약한 시점의 시간이 같이 저장되면 좋을것 같습니다. 시간정보가 추가되면 front단에서 나의 예약 현황 페이지를 그릴 api를 제공할때 오늘,1주일,한달과 같은 형태로 검색필터를 걸어야 하는 요구사항이 생겼을때도 대응하기 좋을것 같아요. 이런 포인트를 잘 고려하는면 새로운 요구사항이 생겨도 확장성을 고려했기 때문에 기존 설계에서 큰 변화 없이 개발이 가능합니다.

2. booking_seat_history

히스토리 테이블을 통해서 예약이 되지 않았어요와 같은 항의가 들어왔을때 잘 체크할 수 있을것 같네요 👏 
booking_seat_history테이블이 어떤 이유때문에 존재해야하나요? booking_seat_history테이블 없이 booking_history테이블만 있는것과 어떤 차이가 있는건가요?

## 트랜잭션에 대해서 조사하는 과제

문제 상황을 잘 인지하고 이를 해결하는 방안을 잘 파악하신것 같아요 💯 

```
문제 상황

공연 예매시, 특정 좌석에 동시에 접근했을 경우 → 동시성 문제 발생 ⇒ [해결] 트랜잭션 락
```


요구사항에 동시예약을 막아야한다는 내용이 있는데, 동시예매를 막기 위해서 어떤 잠금 or 트랜잭션 isolation level 을 사용해서 이를 해결할 수 있을까요?
